import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '../../source/default/tokens/tokens.css';
import { AppContextProvider } from '@/app/context/app';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <AppContextProvider>
        <body className={inter.className}>{children}</body>
      </AppContextProvider>
    </html>
  );
}
