import type { Metadata } from 'next';
import localFont from 'next/font/local';

import '../../source/default/tokens/tokens.css';

const inter = localFont({
  src: '../../source/default/tokens/fonts/inter/Inter.var.woff2',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
